apiVersion: v1
kind: Service
metadata:
  name: qqing-server-service
spec:
  type: NodePort
  ports:
  - port: 25450  
    nodePort: 30450
    targetPort: 25450
    protocol: UDP
  selector:
    app: qping-server
