apiVersion: v1
kind: Service
metadata:
  name: qping-svc-nlb
  namespace: italtelspain
  labels:
    app.kubernetes.io/name: qping-svc-nlb
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-type: nlb
spec:
  type: LoadBalancer
  selector:
      app: qping-server
  ports:
    - name: qping-port
      port: 30450
      targetPort: 25450
      protocol: UDP
